series:
  - title: "7th Time Loop: The Villainess Enjoys a Carefree Life Married to Her Worst Enemy!"
    type: manga
    format: paperback
    author: "Touko Amekawa, Hinoki Kino (Illustrator), Wan Hachipisu (Contribution by)"
    publisher: seven_seas_entertainment
    series_url: "https://sevenseasentertainment.com/series/7th-time-loop-the-villainess-enjoys-a-carefree-life-married-to-her-worst-enemy-manga/"
    status: ongoing
  # A
  - title: "The Apothecary Diaries"
    type: manga
    format: paperback
    author: "Natsu Hyuuga, Nekokurage, Itsuki Nanao (Compiler), Touco Shino (Designed by)"
    publisher: square_enix
    series_url: "https://squareenixmangaandbooks.square-enix-games.com/en-us/series/the-apothecary-diaries"
    status: ongoing
  # K
  - title: "Kill the Villainess"
    type: manwha
    format: paperback
    author: "Haegi (Artist)"
    publisher: yen_press
    series_url: "https://yenpress.com/series/kill-the-villainess"
    status: ongoing
  # M
  - title: "Magic Artisan Dahlia Wilts No More"
    type: manga
    format: paperback
    author: "Hisaya Amagishi, Megumi Sumikawa (Illustrator), KEI (Contribution by)"
    publisher: seven_seas_entertainment
    series_url: "https://sevenseasentertainment.com/series/magic-artisan-dahlia-wilts-no-more-manga/"
    status: ongoing
  # P
  - title: "Pass the Monster Meat, Milady!"
    type: manga
    format: paperback
    author: "Chika Mizube, Kanata Hoshi (Created by), Peperon (Designed by)"
    publisher: kodansha_international
    series_url: "https://kodansha.us/series/pass-the-monster-meat-milady"
    api_url: "https://api.kodansha.us/product/forSeries/765?platform=web&api-version=1.4"
    status: ongoing
  # V
  - title: "Villains Are Destined to Die"
    type: manwha
    format: paperback
    author: "SUOL (Artist), David Odell (Translator)"
    publisher: yen_press
    series_url: "https://yenpress.com/series/villains-are-destined-to-die"
    status: ongoing
  # W
  - title: "Why Raeliana Ended Up at the Duke's Mansion"
    type: manwha
    format: paperback
    author: "Whale (Artist), David Odell (Translator)"
    publisher: yen_press
    series_url: "https://yenpress.com/series/why-raeliana-ended-up-at-the-duke-s-mansion"
    status: complete
  # Y
  - title: "Yakuza Fiancé: Raise wa Tanin ga Ii"
    type: manga
    format: paperback
    author: "Asuka Konishi"
    publisher: seven_seas_entertainment
    series_url: "https://sevenseasentertainment.com/series/yakuza-fiance-raise-wa-tanin-ga-ii/"
    status: ongoing
  - title: "You Can't Bluff the Sharp-Eyed Sister"
    type: manga
    format: paperback
    author: "Yo Asami, Natsu Hyuuga (Created by), Chiho Shinishi (Designed by)"
    publisher: kodansha_international
    series_url: "https://kodansha.us/series/you-cant-bluff-the-sharp-eyed-sister"
    api_url: "https://api.kodansha.us/product/forSeries/879?platform=web&api-version=1.4"
    status: ongoing
sources:
  yen_press: "https://yenpress.com/calendar"
  seven_seas_entertainment: "https://sevenseasentertainment.com/release-dates/"
  square_enix: "https://squareenixmangaandbooks.square-enix-games.com/en-us/release-calendar"
  kodansha_international: "https://kodansha.us/calendar/"